api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views

app_name = 'api'

urlpatterns = [
    path('countries/', views.CountryList.as_view(), name="countries"),
    path('country/<int:pk>/', views.CountryDetail.as_view()),
    path('regions/', views.CountryRegionList.as_view(), name='regions'),
    path('region/<int:pk>/', views.CountryRegionDetail.as_view()),
    path('products/', views.ProductList.as_view(), name='products'),
    path('product/<int:pk>/', views.ProductDetail.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

test_project/urls.py
from django.contrib import admin
from django.urls import path, include

from mainapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.CreateProduct.as_view(), name='send_form'),
    path('load_regions/', views.load_region),
    path('', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('register/', views.UserCreateView.as_view(), name='register')
]

mainapp/models.py
import re

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


class Country(models.Model):
    country_name = models.CharField(max_length=64, verbose_name='страна')

    def __str__(self):
        return self.country_name

    class Meta:
        verbose_name_plural = 'Страны'


class CountryRegion(models.Model):
    region_name = models.CharField(max_length=64, verbose_name='регион страны')
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='country_region')

    class Meta:
        verbose_name_plural = 'Регионы'

    def __str__(self):
        return self.region_name


def validate_field(value):
    result = re.match("^[a-zA-Zа-яА-Я]+|[a-zA-Zа-яА-Я]+$", value)
    if not result:
        raise ValidationError('Допускается только кирилица или латиница. Допускается два слова.',
                              params={'value': value})


class Product(models.Model):
    YEAR_CHOICES = {
        (2018, 2018),
        (2019, 2019),
        (2020, 2020),
        (2021, 2021)
    }
    product_name = models.CharField(max_length=64, verbose_name='Название товара', validators=[validate_field])
    product_grade = models.CharField(max_length=128, verbose_name='Марка товара', blank=True,
                                     validators=[validate_field])
    product_year = models.PositiveIntegerField(verbose_name='Год изготовления', choices=YEAR_CHOICES, blank=True,
                                               null=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE, related_name='country_product')
    region = models.ForeignKey(CountryRegion, on_delete=models.CASCADE, related_name='region_product')

    class Meta:
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.product_name


class Seeker(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='имя на портале')
    age = models.PositiveSmallIntegerField(verbose_name='ваш возраст')
    skills = models.CharField(max_length=256, verbose_name='ваши навыки')

    class Meta:
        verbose_name_plural = 'Соискатели'

mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import inlineformset_factory

from mainapp.models import Product, Seeker


class RecordForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

        help_texts = {
            'product_year': 'поле необязательное',
        }

        labels = {
            'region': 'Регион страны',
            'country': 'Cтрана',
        }

    def __init__(self, *args, **kwargs):
        super(RecordForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['email'] = forms.EmailField(label='Адрес эллектронной почты', required=True)
        self.fields['first_name'] = forms.CharField(max_length=20, label='Фамилия', required=True)
        self.fields['last_name'] = forms.CharField(max_length=20, label='Имя', required=True)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class SeekerForm(forms.ModelForm):
    class Meta:
        model = Seeker
        fields = ('age', 'skills')

    def __init__(self, *args, **kwargs):
        super(SeekerForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 18:
            raise forms.ValidationError('вы слишком молоды')
        return age

mainapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import CreateView
from django.forms import inlineformset_factory

from mainapp.forms import RecordForm, UserForm, SeekerForm
from mainapp.models import CountryRegion, Seeker, User


class CreateProduct(CreateView):
    sent = False
    template_name = 'mainapp/form.html'
    form_class = RecordForm
    success_url = 'send_form'

    def form_valid(self, form):
        self.sent = True
        super(CreateProduct, self).form_valid(form)
        return render(self.request, self.template_name, self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(CreateProduct, self).get_context_data(**kwargs)
        context['sent'] = self.sent
        return context


def load_region(request):
    country = request.GET.get('country')
    region_list = None
    if country:
        region_list = CountryRegion.objects.filter(country=country)
    return render(request, 'mainapp/load_region.html', {'region_list': region_list})


# class UserCreateView(CreateView):
#     template_name = 'mainapp/user_create_form.html'
#     form_class = UserForm
#     success_url = 'send_form'
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['seeker_form'] = SeekerForm()
#         return context
#
#     def form_valid(self, form):
#         user = form.save(commit=False)
#         seeker_form = SeekerForm(self.request.POST, instance=user)
#         if seeker_form.is_valid():
#             user.is_active = False
#             user.save()
#             print('valid')
#             Seeker.objects.create(user=user,
#                                   age=seeker_form.cleaned_data['age'],
#                                   skills=seeker_form.cleaned_data['skills'])
#             return HttpResponseRedirect(reverse(self.success_url))
#         return render(self.request, self.template_name, {'form': form, 'seeker_form': seeker_form})


class UserCreateView(CreateView):
    template_name = 'mainapp/user_create_form.html'
    form_class = UserForm
    # success_url = 'send_form'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context['seeker_form'] = SeekerForm(self.request.POST)
        else:
            context['seeker_form'] = SeekerForm()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        seeker_form = context['seeker_form']
        if form.is_valid() and seeker_form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            seeker = seeker_form.save(commit=False)
            seeker.user = user
            seeker.save()
            return super().form_valid(form)
            # return HttpResponseRedirect(reverse('send_form'))
        return render(self.request, self.template_name, context)

    def get_success_url(self):
        return reverse('send_form')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>{% block title %} {{ title|title }} {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet">
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-md navbar-dark bg-dark" style="background: #423c38;">
		  <div class="container-fluid">
			  <a class="navbar-brand" href="#"><strong>Test Project</strong></a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
			  <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
			    <li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown">API</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a href="{% url 'api:countries' %}" class="dropdown-item">страны</a>
						<a href="{% url 'api:regions' %}" class="dropdown-item">регионы</a>
						<a href="{% url 'api:products' %}" class="dropdown-item">продукты</a>
					</div>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'admin:login' %}">Админка</a>
				</li>
			  </ul>
			</div>
		  </div>
		</nav>
	</header>

    {% block content %}

    {% endblock %}
	<footer>
		<div class="container-fluid bg-dark">
			<div class="row">
				<div class="col-12"><p class=" mt-4 ml-5 copyright">{% now 'Y' %}</p></div>
			</div>
		</div>
	</footer>
	{% block js %}
	<script src="{% static 'js/jquery-3.6.0-min.js' %}"></script>
	<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
	<script src="{% static 'js/script.js' %}"></script>
	{% endblock %}
</body>
</html>

mainapp/templates/mainapp/form.html
{% extends 'mainapp/base.html' %}

{% load static %}

{% block content %}
<div class="container my-5">
    <div class="row justify-content-center">
        <div class="col-11 col-sm-7 col-md-6">
            {% if sent %}
                <p class="my-5 h5 font-italic">Форма успешно отправлена</p>
                <a class="my-5 btn btn-outline-primary" role="button" href="{% url 'send_form' %}">отправить снова</a>
            {% else %}
                <h4 class="text-center mb-3 font-italic">Форма отправки</h4>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="form-control btn btn-outline-primary" type="submit" value="отправить">
                </form>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/load_region.html
<option value="">---------</option>
{% for item in region_list %}
<option value="{{ item.pk }}">{{ item.region_name }}</option>
{% endfor %}

mainapp/templates/mainapp/user_create_form.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}Регистрация{% endblock title %}
{% block content %}
<div class="container my-5">
    <h1 class="mb-5 text-center font-italic">Регистрация</h1>
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <form class="form-horizontal" action="#" method="post"
                  enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                {{ seeker_form.as_p }}
                <input class="form-control btn btn-outline-primary mt-4 mb-5" type="submit" value="зарегистрироваться">
            </form>
        </div>
    </div>
</div>
{% endblock %}